# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1

[fr]
languageName = "French"
languagedirection = "ltr"
title = "Site exemple"
weight = 1